name: Build Templates
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONUTF8: 1
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4

      - name: Install Chinese (Simplified) Supplemental Fonts
        shell: pwsh
        run: Add-WindowsCapability -Online -Name "Language.Fonts.Hans~~~und-HANS~0.0.1.0"
      - name: Install Chinese (Traditional) Supplemental Fonts
        shell: pwsh
        run: Add-WindowsCapability -Online -Name "Language.Fonts.Hant~~~und-HANT~0.0.1.0"
      - run: typst fonts

      - run: python3 ci/mode_switch.py dev templates
      - run: python3 ci/build.py
      - uses: actions/upload-artifact@v4
        with:
          path: build/*.pdf
